version: "3"

services:
  api:
    build: .
    container_name: api_rentcars
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - backend


  database:
    image: postgres
    container_name: database_rentcars
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mrktplc@1
      - POSTGRES_DB=rentcarsDB
    volumes:
      - pgdata:/data/postgres
    networks:
      - backend

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: "bridge"
